### ISSUE TITLE
Place component snapping point

### ISSUE THREAD

**Issue by ChrisMcSomething** [thomthom/sketchup-place-component#2]
In Sketchup 2019 the point that the component being placed was set by the point at which the move tool was last used. In Sketchup 2021 the it appears that the snapping point is the group or components axis point which drastically slows the workflow. Is this due to a limitation in Sketchup 2021 or was there a change in what is defined as the snapping point? Is it possible to make it so that the snapping point is set to the point used with the move tool like in previous versions? 

Thank you! I love the tool!

**Comment by thomthom** [comment]
There was a change in SketchUp such that it will always use the group/component origin. No option to re-enable the old behaviour I'm afraid.
